USE master;

CREATE DATABASE PV_522_DDL
ON
(
	NAME		=	PV_522_DDL,
	FILENAME	=	'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_522_DDL.mdf',
	SIZE		=	8 MB,
	MAXSIZE		=	500MB,
	FILEGROWTH	=	8MB
)
LOG ON
(
	NAME		=	PV_522_DDL_Log,
	FILENAME	=	'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_522_DDL.ldf',
	SIZE		=	8MB,
	MAXSIZE		=	500MB,
	FILEGROWTH	=	8MB
);